name: "granite-embedding-english-r2"
backend: "vllm"

input [
  {
    name: "text"
    data_type: TYPE_STRING
    dims: [ -1 ]
  }
]

output [
  {
    name: "embeddings"
    data_type: TYPE_FP32
    dims: [ -1 ]
  }
]

parameters {
  key: "model"
  value: { string_value: "/models/granite-embedding-english-r2" }
}

parameters {
  key: "task"
  value: { string_value: "embedding" }
}

parameters {
  key: "use_streaming"
  value: { string_value: "false" }
}
