general_settings:
  user_header_name: X-OpenWebUI-User-Id
litellm_settings:
  public_model_groups:
    - gpt-oss-120b
model_list:
  - litellm_params:
      api_base: http://hostproxy:7002/v1
      api_key: os.environ/VLLM_API_KEY
      model: hosted_vllm/openai/gpt-oss-120b
    model_name: gpt-oss-120b
  - litellm_params:
      api_base: http://hostproxy:7001/v1
      api_key: os.environ/VLLM_API_KEY
      model: hosted_vllm/openai/gpt-oss-20b
    model_name: gpt-oss-120b
  - model_name: Qwen3-Coder-30B-A3B
    litellm_params:
      model: triton/Qwen3-Coder-30B-A3B-Instruct-W4A16"
      api_base: http://tritonserver:8000/v2/models/Qwen3-Coder-30B-A3B-Instruct-W4A16/generate
      drop_params: true
