general_settings:
  user_header_name: X-OpenWebUI-User-Id

model_list:
#  - model_name: Qwen2-7B-Instruct
#    litellm_params:
#      model: hosted_vllm/Qwen/Qwen2-7B-Instruct
#      api_base: http://hostproxy:7000/v1
#      api_key: os.environ/VLLM_API_KEY

#  - model_name: Qwen3-Coder-30B-A3B-Instruct
#    litellm_params:
#      model: hosted_vllm/Qwen/Qwen3-Coder-30B-A3B-Instruct
#      api_base: http://hostproxy:7001/v1
#      api_key: "os.environ/VLLM_API_KEY"

  - model_name: gpt-oss-120b
    litellm_params:
      model: hosted_vllm/openai/gpt-oss-120b
      api_base: http://hostproxy:7002/v1
      api_key: "os.environ/VLLM_API_KEY"
