general_settings:
  user_header_name: X-OpenWebUI-User-Id
litellm_settings:
  public_model_groups:
    - gpt-oss-120b
    - gpt-oss-20b
model_list:
  - litellm_params:
      api_base: http://hostproxy:7002/v1
      api_key: os.environ/VLLM_API_KEY
      model: hosted_vllm/openai/gpt-oss-120b
    model_name: gpt-oss-120b
  - model_name: triton-Qwen3-8B
    litellm_params:
      model: triton/Qwen3-8B"
      api_base: http://chris-gpu-proxy:8000/generate
