general_settings:
  user_header_name: X-OpenWebUI-User-Id
litellm_settings:
  public_model_groups:
    - gpt-oss-120b
    - Qwen3-8B
    - granite-embedding-english-r2
#    - mxbai-embed-large-v1
model_list:
  - litellm_params:
      api_base: http://hostproxy:7002/v1
      api_key: os.environ/VLLM_API_KEY
      model: hosted_vllm/openai/gpt-oss-120b
    model_name: gpt-oss-120b
  - model_name: Qwen3-Coder-30B-A3B
    litellm_params:
      model: triton/Qwen3-Coder-30B-A3B-Instruct-W4A16"
      api_base: http://chris-gpu-proxy:8000/v2/models/Qwen3-Coder-30B-A3B-Instruct-W4A16/generate
      drop_params: true
  - model_name: granite-embedding-english-r2
    litellm_params:
      model: openai/granite-embedding-english-r2"
      api_base: http://triton-grpc-proxy:8005/v1
#  - model_name: mxbai-embed-large-v1
#    litellm_params:
#      model: triton/mxbai-embed-large-v1"
#      api_base: http://chris-gpu-proxy:8000/v2/models/mxbai-embed-large-v1/embeddings
